startRecording config parameter and auto recording start changes added
talview/lib-jitsi-meet pull request #1
Opened 2022-10-13 14:25 UTC by harishnv

2022-10-17 03:23 UTC, manquer requested changes
There is no dep change why lock file changed?

2022-10-17 03:23 UTC, manquer commented on JitsiConference.js
> +
try catch ?

2022-10-17 03:23 UTC, manquer commented on JitsiConference.js
> +    this.onStartRecording({ test: true });
test true ?

2022-10-18 02:56 UTC, harishnv commented on JitsiConference.js
> +
implemented

2022-10-18 02:56 UTC, harishnv commented on JitsiConference.js
> +    this.onStartRecording({ test: true });
updated

2022-10-19 22:43 UTC, manquer approved these changes

2022-10-19 22:43 UTC, merged